[project]
name = "dtekschedule"
version = "0.1.0"
description = "A simple Selenium scrapper for DTEK shutdown schedules"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.2",
    "gunicorn>=23.0.0",
    "selenium>=4.39.0",
]
